In [1]:
pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB 640.0 kB/s eta 0:00:20
   ---------------------------------------- 0.0/12.6 MB 435.7 kB/s eta 0:00:29
   ---------------------------------------- 0.1/12.6 MB 563.7 kB/s eta 0:00:23
   ---------------------------------------- 0.1/12.6 MB 722.1 kB/s eta 0:00:18
    --------------------------------------- 0.2/12.6 MB 1.1 MB/s eta 0:00:12
   - -------------------------------------- 0.3/12.6 MB 1.3 MB/s eta 0:00:10
   - -------------------------------------- 0.4/12.6 MB 1.4 MB/s eta 0:00:09
   - -------------------------------------- 0.4/12.6 MB 1.1 MB/s eta 0:00:11
   -- ------------------------------------- 0.6/12.6 MB 1.6 MB/s eta 0:00:08
   -- ------------------------------------- 0.8/12.6 MB 1.8 MB/s eta 0:00:07
   --- ------------------------------------ 1.0/12.6 MB 2.1 MB/s eta 0:00:06
   --- ------------------------------------ 1.2/12.6 MB 2.2 MB/s eta 0:00:0


[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [64]:
import numpy as np

In [11]:
my_list = [1,2,3,4]
my_list = my_list *2
array = np.array([1,2,3,4])
array = array*5
print(array)

[ 5 10 15 20]


In [65]:
array = np.array([[["a",'g','f']],
                  [["g",'s','h']],
                  [["e",'m','y']]])

word = array[0,0,0] + array[1,0,1] + array[2,0,1]
print(word)
print(array.shape)

asm
(3, 1, 3)


In [79]:
array=np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [13,14,15,16]])
print(array[2:,2:])

[[11 12]
 [15 16]]


In [87]:
array=np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [13,14,15,16]])
array =array * 10
print(array)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]


In [103]:
array1 = np.array([1,2,3,4,5]) 
array2 = np.array([6,7,8,9,10]) 
array3 = array1 + array2
array4 = array1 - array2
array5 = array1 * array2
array6 = array1 // array2
print(max(array1))
print(array4)
print(array5)
print(array6)


5
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0 0 0 0 0]


In [97]:
import numpy as np

arr = np.array([1.6665, 4.564, 9.85, 16.6545])
result = np.ceil(arr)
print(result)


[ 2.  5. 10. 17.]


In [ ]:
array = np.array([1,2,3,5,34,5,8,72,5,28])
print(np.sqrt(array))


[  5  10  15  25 170  25  40 360  25 140]
[  5  10  15  25 170  25  40 360  25 140]
[ 6  7  8 10 39 10 13 77 10 33]
[ 0  0  0  1  6  1  1 14  1  5]
[ 0.2  0.4  0.6  1.   6.8  1.   1.6 14.4  1.   5.6]
[-4 -3 -2  0 29  0  3 67  0 23]


In [108]:
score = np.array([100,90,55,62,85])
print(score <= 100)
score[score < 60 ] = 0
print(score)



[ True  True  True  True  True]
[100  90   0  62  85]


In [154]:
array1 = np.array([[1,2,3,4,5,6,7,8,9,10]])

array22 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

print(array1.shape)
print(array2.shape)
print(array1 * array22)
print(array1 . array22)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


AttributeError: 'numpy.ndarray' object has no attribute 'array22'

In [153]:
array =np.array([[1,2,3,5,4,5],
                 [6,7,8,5,9,10] ])
print(np.sum(array , axis= 1))
print(np.sum(array))
print(np.mean(array))
print(np.std(array))
print(np.argmin(array))
print(np.max(array))

[20 45]
65
5.416666666666667
2.628635049264584
0
10


In [162]:
v1 = np.array([10,6,20])
v2 = np.array([5,10,14])
print(v1)
print(v1 - v2)



[10  6 20]
[ 5 -4  6]


In [163]:
print(v1.dot(v2))

390


In [168]:
m1 = np.array([ [1,2,3],
                [4,5,6],
                [7,8,9]])
print(m1)
print('=============================')
m2 = np.array([ [0,2,3],
                [8,15,6],
                [7,8,2]])
print(m1  .dot(m2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 37  56  21]
 [ 82 131  54]
 [127 206  87]]


In [171]:
s = np.array(5525)
print(s.ndim) 

0


In [177]:
v1 = np.array([1,2,3])
print(v1.ndim)
print(v1.shape)



1
(3,)


In [176]:
m1 = np.array([[1,2,3],
               [2,5,7],
               [9,8,7]])



print(m1.ndim)
print(m1.shape)



2
(3, 3)


In [173]:
class Student : 
    def __init__(self ,name):
        self.name = name

    @property
    def get_info(self) :
         
         return f"your name is {self.name}"


In [174]:
s1 = Student("MOHAMED")
s1.get_info

'your name is MOHAMED'

In [185]:
ages = np.array([[50,20,16,17,15,46,99], 
                  [25,15,46,85,45,12,34]])

teenagers = ages [ages < 18]
adults = ages[(ages >= 18) | (ages<65)] 
evens = ages[ages % 2 == 0]
odd = ages [ages % 2 != 0 ]
print(odd)
print(evens)

[17 15 99 25 15 85 45]
[50 20 16 46 46 12 34]


In [640]:
ages = np.array([[50,20,16,17,15,46,99], 
                  [25,15,46,85,45,12,34]])


age2 = np.array([[500,201,2146,147,155,446,5], 
                  [255,165,463,8215,4253,12123,334]])



age3 = np.hstack((age2,ages))

print(age3)

[[  500   201  2146   147   155   446     5    50    20    16    17    15
     46    99]
 [  255   165   463  8215  4253 12123   334    25    15    46    85    45
     12    34]]


In [192]:
ages = np.array([[50,20,16,17,15,46,99], 
                  [25,15,46,85,45,12,34]])


adult = np.where((ages > 18),ages , 0)
print(adult)
print (ages)

[[50 20  0  0  0 46 99]
 [25  0 46 85 45  0 34]]
[[50 20 16 17 15 46 99]
 [25 15 46 85 45 12 34]]


In [195]:
vec1 = np.array([1,2,3,4])
met_1 = vec1.reshape(2,2)
print(met_1)

[[1 2]
 [3 4]]


In [196]:
vec_2 = np.array([1,2,3,4])
met_2 = vec_2.reshape(vec_2.shape[0],1)

In [237]:
vec2 = np.array([1,2,3,4,5])
met_3 = vec_2[:,None]
print(met_3)

[[1]
 [2]
 [3]
 [4]]


In [239]:
mat_3 = np.array([[1.2,2,3],
                  [4,5,6],
                  [7,8,9]])

print(mat_3.dtype)

float64


In [ ]:
class C :
    x = 3 
o1 = C()



mat_3 = np.array([[1.2,2,3],
                  [4,5,6],
                  [1,8,9]])

print(mat_3.dtype)


object


In [246]:
mat_3 = np.array([[1.2,2,3],
                  ['4',5,6],
                  [1,8,9]])

mat= mat_3.astype(float)
print(mat)


[[1.2 2.  3. ]
 [4.  5.  6. ]
 [1.  8.  9. ]]


In [ ]:
v1 = np.array([[1,2,3,4,5],
               [6,7,8,9,10]])

v2 

AttributeError: 'numpy.ndarray' object has no attribute 'full'

In [297]:
mat89 = np.zeros((2,2))
num = input("enter num")

mat = np.where(mat89 != 0 ,mat89 ,num)
print(mat)

[['5' '5']
 ['5' '5']]


In [236]:
def reshape (mat , y) :
    mat = vec_2[:,None]
    print(mat)
    

In [303]:

def mat (num1 , num2):
    mat = np.ones((num1,num2))
    print(mat)   

In [305]:
mat(5,5)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [308]:
v2 = np.full((3,3),5)
v2

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [312]:
angels = np.arange(0,721,90)
angels

array([  0,  90, 180, 270, 360, 450, 540, 630, 720])

In [315]:
vec = np.linspace(0,100 ,num=10)
vec

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [421]:
rng= np.random.default_rng()
print(rng.integers(1,9,(5,5)))

[[3 6 7 5 3]
 [8 7 1 6 2]
 [7 6 7 5 8]
 [6 8 1 8 6]
 [2 5 1 2 8]]


In [ ]:
print(np.random.uniform(5,1,(50,50)))

[[2.62229407 3.67881018 2.25682304 ... 4.36926542 4.90731169 3.13375977]
 [2.57574211 3.66039753 1.74612218 ... 2.43195205 2.44757224 4.88107649]
 [1.81149833 2.95165438 3.38683782 ... 1.12350916 3.32158635 2.30563316]
 ...
 [4.47529372 1.3880389  2.55762714 ... 4.18096715 2.11504715 2.81430503]
 [4.68467209 3.89665232 2.81831596 ... 3.95749031 4.0211347  4.76766493]
 [3.09030843 4.7769268  4.06088634 ... 3.45749761 3.07487375 3.40849556]]


In [487]:
ara=np.array([1,2,3,4,5])
rng = np.random.default_rng()
rng.shuffle(ara)
print(ara
)

[1 5 3 4 2]


In [234]:
def reshape (mat ) :
    mat = mat.reshape(mat.shape[0],1)
    print(mat)
    

In [235]:
reshape(np.array([1,2,4,2]))

[[1]
 [2]
 [4]
 [2]]


In [ ]:
arr =np.array([1,2,3,4])
arr.reshape(arr.shape[0],1)


array([[1],
       [2],
       [3],
       [4]])

In [530]:
def array_reshape (arr , rows = -1 , cols = -1):

    arr = np.array(arr)
    return arr.reshape(rows ,cols)


In [540]:
vex =[1,2,4,5,4,5]
array_reshape(vex,2,3)


array([[1, 2, 4],
       [5, 4, 5]])

In [542]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [544]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [545]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [561]:
mat = np.array([1,2,3,5,4,6,6,4,5])
mat = mat.reshape(3,3)
print(mat)
print("===============================")
mat1 = np.full((3,3),3)
print(mat1)
mat2 = np.where( [mat1 == 3] ,6 , 7 )
print("===============================")
print(mat2)



[[1 2 3]
 [5 4 6]
 [6 4 5]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]
[[[6 6 6]
  [6 6 6]
  [6 6 6]]]


In [570]:
angels = np.arange(0,101,10)
v = angels.reshape(angels.shape[0],1)
v

array([[  0],
       [ 10],
       [ 20],
       [ 30],
       [ 40],
       [ 50],
       [ 60],
       [ 70],
       [ 80],
       [ 90],
       [100]])

In [571]:
v1 = np.linspace (0,100,10)
v1

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [573]:
I = np.identity(5,str)
I

array([['1', '', '', '', ''],
       ['', '1', '', '', ''],
       ['', '', '1', '', ''],
       ['', '', '', '1', ''],
       ['', '', '', '', '1']], dtype='<U1')

In [626]:
randam = np.random.randint(0,11,(5,5))
print(randam)

[[8 9 2 2 5]
 [5 6 0 7 0]
 [1 1 1 7 0]
 [6 4 3 4 3]
 [2 6 3 5 5]]


In [627]:
mat1= np.ones((4,4))
mat2 = np.zeros((5,5))

np.savez("mohamed",ones_mat=mat1,zero=mat2)

In [636]:
with np.load('mohamed.npz') as file :
    file = np.load("mohamed.npz")
    mat1= file['ones_mat']
    print(mat1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [2]:
print(np.__version__)

2.4.0
