In [141]:
import numpy as np
def smart_array_generator(mode , shape : tuple , low=-1 , high=-1) :
    if mode == 'zeros' :
        array = np.zeros(shape)
        return array
    elif mode == 'ones' :
        array = np.ones(shape)
        return array
    elif mode == 'identity' :
        array = np.identity(shape)
        return array

    elif mode == 'random' :
        array = np.random.randint(low , high , size=shape)
        return array


In [157]:
print( smart_array_generator('random', (5,5),0,100))

[[80 34 92 60 32]
 [18 33 75 81 47]
 [86 43  2 79 81]
 [29 16 17 85 86]
 [81 49  4 88 87]]


In [181]:
def apply_threshold(arr , threshold , replacment_value= -1):
    array1 = np.array(arr)
    array2 = np.where([array1 > threshold],replacment_value,array1)
    return array2


In [182]:
r = [25,30,85,22,90]
apply_threshold(r,80,-1)


array([[25, 30, -1, 22, -1]])